-- Queue of quote update tasks. A row is created by POST /quotes/updates and
-- driven to a terminal status by the background worker; the HTTP handler never
-- contacts the rate provider itself.
CREATE TABLE quote_updates (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    pair       text        NOT NULL CHECK (pair ~ '^[A-Z]{3}/[A-Z]{3}$'),
    status     text        NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending', 'in_progress', 'done', 'failed')),
    -- Incremented when a worker claims the task, so it counts how many times
    -- processing was started. Normally 1. It bounds the recovery loop below:
    -- without it, a task that reliably kills its worker would be released back
    -- to 'pending' forever.
    attempts   smallint    NOT NULL DEFAULT 0,
    -- Normalised failure reason. Raw provider errors and upstream URLs stay in
    -- the logs and must not leak here, since this field is served to clients.
    error      text,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Written by every status transition. For 'in_progress' rows this is the
    -- claim time, because claiming is the only writer of that status, and the
    -- recovery pass measures staleness from it. Generated by the database so
    -- that it is compared against the same clock that produced it.
    updated_at timestamptz NOT NULL DEFAULT now(),
    -- A failed task must carry a reason: the API serves 'error' alongside that
    -- status, so a null here would answer the client with a bare failure. Stated
    -- in one direction only, which leaves 'error' free to hold a reason on a
    -- task that has not reached a terminal status.
    CONSTRAINT quote_updates_failed_has_reason
        CHECK (status <> 'failed' OR error IS NOT NULL)
);

-- Claim path: oldest pending task first. Partial, so it stays small no matter
-- how much finished history the table accumulates.
CREATE INDEX quote_updates_pending_idx
    ON quote_updates (created_at)
    WHERE status = 'pending';

-- Recovery path: tasks left in 'in_progress' by a worker that died between the
-- claim commit and the finalisation transaction. Nothing releases those rows on
-- their own -- the row lock was already gone when the process disappeared.
CREATE INDEX quote_updates_in_progress_idx
    ON quote_updates (updated_at)
    WHERE status = 'in_progress';

-- Successfully fetched rates, one row per completed update.
--
-- 'pair' is a denormalised copy of quote_updates.pair. Without it the latest
-- quote lookup would filter on one table and sort on the other, which no single
-- index can serve; with it the whole query is one scan of the index below.
-- The copies cannot drift: both are immutable after insert and are written from
-- the same value by the finalisation transaction, which is this table's only
-- writer.
CREATE TABLE quotes (
    -- Also the foreign key: exactly one quote per update, enforced by the
    -- primary key rather than by convention.
    update_id  uuid           PRIMARY KEY REFERENCES quote_updates (id),
    pair       text           NOT NULL,
    rate       numeric(20,10) NOT NULL CHECK (rate > 0),
    -- The day the rate is valid for, taken from the provider's "date" field.
    -- ECB reference rates are daily and published on working days only, so this
    -- can lag fetched_at by up to several days over a weekend. Stored as a date
    -- because the provider exposes no publication instant at all.
    rate_date  date           NOT NULL,
    -- When this service successfully received the rate. Generated by the
    -- application at the moment the provider call returned, not by now(), which
    -- would be the start of the transaction that opens afterwards.
    fetched_at timestamptz    NOT NULL
);

-- Serves GET /quotes/latest: the predicate and the ordering both come from this
-- index, so the answer is the first entry it yields regardless of history size.
CREATE INDEX quotes_pair_fetched_at_idx
    ON quotes (pair, fetched_at DESC);
