// Package postgres holds everything that talks to PostgreSQL.
package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	"github.com/llukmann/currency-quotes-service/internal/domain"
)

// Every statement here that moves a task between statuses has to carry
// updated_at = now(), and nothing in the schema enforces that.
type Repository struct {
	pool *pgxpool.Pool
	// Nothing deletes an expired binding: the lookup stops seeing it, and the
	// next post carrying that key takes the row over.
	keyTTL time.Duration
}

// Compose already gates the service on the postgres healthcheck, so this only
// has to cover an unreachable or misconfigured host, not a slow boot.
const pingTimeout = 10 * time.Second

// The pool opens its connections on demand, so one is asked for here: without
// it a host that cannot be reached at all would first be reported as a failed
// request, long after the start it should have stopped.
func New(ctx context.Context, databaseURL string, keyTTL time.Duration) (*Repository, error) {
	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		return nil, fmt.Errorf("connect to database: %w", err)
	}

	pingCtx, cancel := context.WithTimeout(ctx, pingTimeout)
	defer cancel()

	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()

		return nil, fmt.Errorf("connect to database: %w", err)
	}

	return &Repository{pool: pool, keyTTL: keyTTL}, nil
}

func (r *Repository) Close() {
	r.pool.Close()
}

// So one statement can be issued from either the pool or a transaction.
type querier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// The task returned is not always a new one: an unfinished task for the same
// pair, or a live idempotency key, is answered with the task that exists.
//
// The task and its binding are written in one transaction, so that rolling back
// takes the task with it: written afterwards, a lost race would leave a task
// whose identifier reached nobody.
func (r *Repository) CreateTask(ctx context.Context, pair domain.Pair, key *uuid.UUID) (domain.UpdateTask, error) {
	if key == nil {
		return insertTask(ctx, r.pool, pair)
	}

	// A fast path and nothing more. What makes the answer right when two
	// requests race is the constraint below, never this read.
	task, found, err := r.taskByKey(ctx, *key)
	if err != nil {
		return domain.UpdateTask{}, err
	}
	if found {
		return replayTask(task, pair)
	}

	return r.createTaskWithKey(ctx, pair, *key)
}

func (r *Repository) createTaskWithKey(ctx context.Context, pair domain.Pair, key uuid.UUID) (domain.UpdateTask, error) {
	// Three outcomes in one statement. No row for this key: it is bound here.
	// A row past its lifetime: it is taken over, which is the only thing that
	// ever ends a binding now that nothing deletes one. A row that still holds:
	// the condition on the update fails, no row comes back, and that is how a
	// key already spoken for is reported -- an insert that raised a duplicate
	// key instead would be indistinguishable from one that hit an expired row.
	const bindQuery = `
		INSERT INTO idempotency_keys (key, update_id)
		VALUES ($1, $2)
		ON CONFLICT (key) DO UPDATE
		   SET update_id = EXCLUDED.update_id, created_at = now()
		 WHERE idempotency_keys.created_at <= now() - make_interval(secs => $3)
		RETURNING key`

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return domain.UpdateTask{}, fmt.Errorf("create task: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// The order is forced rather than chosen: the identifier is generated by
	// the database, so there is nothing to bind a key to until the task exists.
	task, err := insertTask(ctx, tx, pair)
	if err != nil {
		return domain.UpdateTask{}, err
	}

	var bound uuid.UUID

	err = tx.QueryRow(ctx, bindQuery, key, task.ID, r.keyTTL.Seconds()).Scan(&bound)

	switch {
	case err == nil:
		if err := tx.Commit(ctx); err != nil {
			return domain.UpdateTask{}, fmt.Errorf("create task: commit: %w", err)
		}

		return task, nil

	case errors.Is(err, pgx.ErrNoRows):
		// Rolling back drops the task written a moment ago along with it, which
		// is the whole reason both are here.
		//
		// The holder has committed by now, and that is not an assumption: a
		// statement conflicting with an uncommitted duplicate waits for the
		// other transaction to end.
		if err := tx.Rollback(ctx); err != nil {
			return domain.UpdateTask{}, fmt.Errorf("create task: rollback: %w", err)
		}

		return r.replayByKey(ctx, key, pair)

	default:
		return domain.UpdateTask{}, fmt.Errorf("create task: bind key: %w", err)
	}
}

func (r *Repository) replayByKey(ctx context.Context, key uuid.UUID, pair domain.Pair) (domain.UpdateTask, error) {
	task, found, err := r.taskByKey(ctx, key)
	if err != nil {
		return domain.UpdateTask{}, err
	}
	if !found {
		// The two statements read the clock at two instants, so a binding that
		// held when the insert refused it can be expired by the time of this
		// read. Reported rather than retried around: the window is one round
		// trip at the far end of a lifetime measured in hours.
		return domain.UpdateTask{}, fmt.Errorf("create task: key %s is held but binds no task", key)
	}

	return replayTask(task, pair)
}

// The pair of the bound task is enough to tell whether it was the same
// request: a key is only ever bound to a task queued for the pair it arrived
// with.
func replayTask(task domain.UpdateTask, pair domain.Pair) (domain.UpdateTask, error) {
	if task.Pair != pair {
		return domain.UpdateTask{}, domain.ErrKeyConflict
	}

	return task, nil
}

// Age is part of the condition, and this is where the lifetime of a binding is
// enforced: nothing deletes an expired row, the lookup stops seeing it.
func (r *Repository) taskByKey(ctx context.Context, key uuid.UUID) (domain.UpdateTask, bool, error) {
	const query = `
		SELECT u.id, u.pair, u.status, u.attempts, COALESCE(u.error, ''), u.created_at, u.updated_at
		  FROM idempotency_keys k
		  JOIN quote_updates u ON u.id = k.update_id
		 WHERE k.key = $1
		   AND k.created_at > now() - make_interval(secs => $2)`

	task, err := scanTask(r.pool.QueryRow(ctx, query, key, r.keyTTL.Seconds()))

	if errors.Is(err, pgx.ErrNoRows) {
		return domain.UpdateTask{}, false, nil
	}
	if err != nil {
		return domain.UpdateTask{}, false, fmt.Errorf("task by key %s: %w", key, err)
	}

	return task, true, nil
}

// The conflict is resolved by an update that changes nothing, purely so the
// statement has a row to return: DO NOTHING returns none, and a second query
// opens a window in which the other task finishes.
//
// What it must never touch is updated_at. For a task in progress that column is
// the recovery pass's clock, and posts on a busy pair would push the threshold
// ahead of itself for as long as they kept arriving.
func insertTask(ctx context.Context, q querier, pair domain.Pair) (domain.UpdateTask, error) {
	const query = `
		INSERT INTO quote_updates (pair)
		VALUES ($1)
		ON CONFLICT (pair) WHERE status IN ('pending', 'in_progress')
		DO UPDATE SET pair = quote_updates.pair
		RETURNING id, pair, status, attempts, COALESCE(error, ''), created_at, updated_at`

	t, err := scanTask(q.QueryRow(ctx, query, pair))
	if err != nil {
		return domain.UpdateTask{}, fmt.Errorf("create task: %w", err)
	}

	return t, nil
}

// A quote row exists for precisely the tasks in StatusDone, since the
// finalisation writes both in one transaction, so the join answers in a single
// round trip.
func (r *Repository) GetTask(ctx context.Context, id uuid.UUID) (domain.TaskDetails, error) {
	const query = `
		SELECT u.id, u.pair, u.status, u.attempts, COALESCE(u.error, ''), u.created_at, u.updated_at,
		       q.update_id, q.pair, q.rate::text, q.rate_date, q.fetched_at
		  FROM quote_updates u
		  LEFT JOIN quotes q ON q.update_id = u.id
		 WHERE u.id = $1`

	var (
		d domain.TaskDetails
		// Null for every task that has not completed, hence the pointers.
		quoteID   *uuid.UUID
		quotePair *domain.Pair
		rawRate   *string
		rateDate  *time.Time
		fetchedAt *time.Time
	)

	err := r.pool.QueryRow(ctx, query, id).Scan(
		&d.Task.ID, &d.Task.Pair, &d.Task.Status, &d.Task.Attempts,
		&d.Task.Error, &d.Task.CreatedAt, &d.Task.UpdatedAt,
		&quoteID, &quotePair, &rawRate, &rateDate, &fetchedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.TaskDetails{}, fmt.Errorf("get task %s: %w", id, domain.ErrNotFound)
	}
	if err != nil {
		return domain.TaskDetails{}, fmt.Errorf("get task %s: %w", id, err)
	}

	if quoteID == nil {
		return d, nil
	}

	rate, err := decimal.NewFromString(*rawRate)
	if err != nil {
		return domain.TaskDetails{}, fmt.Errorf("get task %s: parse rate %q: %w", id, *rawRate, err)
	}

	d.Quote = &domain.Quote{
		UpdateID:  *quoteID,
		Pair:      *quotePair,
		Rate:      rate,
		RateDate:  *rateDate,
		FetchedAt: *fetchedAt,
	}

	return d, nil
}

func (r *Repository) GetLatestQuote(ctx context.Context, pair domain.Pair) (domain.Quote, error) {
	// Ordered by fetched_at rather than rate_date: a weekend leaves several
	// rows sharing one rate_date, and their order would be undefined. Both the
	// filter and the ordering are served by quotes_pair_fetched_at_idx.
	const query = `
		SELECT update_id, pair, rate::text, rate_date, fetched_at
		  FROM quotes
		 WHERE pair = $1
		 ORDER BY fetched_at DESC
		 LIMIT 1`

	var (
		q       domain.Quote
		rawRate string
	)

	err := r.pool.QueryRow(ctx, query, pair).Scan(&q.UpdateID, &q.Pair, &rawRate, &q.RateDate, &q.FetchedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Quote{}, fmt.Errorf("get latest quote for %s: %w", pair, domain.ErrNotFound)
	}
	if err != nil {
		return domain.Quote{}, fmt.Errorf("get latest quote for %s: %w", pair, err)
	}

	if q.Rate, err = decimal.NewFromString(rawRate); err != nil {
		return domain.Quote{}, fmt.Errorf("get latest quote for %s: parse rate %q: %w", pair, rawRate, err)
	}

	return q, nil
}

// Selecting and marking are one statement on purpose: apart, another worker
// reads the row in between and the provider is called twice for one task.
// SKIP LOCKED is what keeps a pool from queueing up behind the oldest row.
//
// The row lock lasts only until this statement commits, so from then on the
// only thing saying the task is taken is its status -- which is why the
// recovery pass exists and why finalising has to prove its claim.
func (r *Repository) ClaimTask(ctx context.Context) (domain.UpdateTask, bool, error) {
	// attempts is incremented here rather than on failure: it counts how many
	// times processing was started, which is what the recovery pass bounds.
	const query = `
		UPDATE quote_updates
		   SET status     = 'in_progress',
		       attempts   = attempts + 1,
		       updated_at = now()
		 WHERE id = (
		       SELECT id
		         FROM quote_updates
		        WHERE status = 'pending'
		        ORDER BY created_at
		        LIMIT 1
		          FOR UPDATE SKIP LOCKED
		 )
		RETURNING id, pair, status, attempts, COALESCE(error, ''), created_at, updated_at`

	t, err := scanTask(r.pool.QueryRow(ctx, query))
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.UpdateTask{}, false, nil
	}
	if err != nil {
		return domain.UpdateTask{}, false, fmt.Errorf("claim task: %w", err)
	}

	return t, true, nil
}

// One transaction: a quote whose task is not finished would be served by
// GET /quotes/latest under a task that still claims to be running.
//
// claim must be the task as ClaimTask returned it: its attempts value
// identifies the claim, and matching on it is what a status check cannot do,
// since a task taken away and claimed again carries the status back.
//
// The task is closed before the quote is inserted, so a lost claim leaves no
// row behind in quotes.
func (r *Repository) CompleteTask(
	ctx context.Context,
	claim domain.UpdateTask,
	rate decimal.Decimal,
	rateDate time.Time,
	fetchedAt time.Time,
) error {
	const closeTask = `
		UPDATE quote_updates
		   SET status     = 'done',
		       error      = NULL,
		       updated_at = now()
		 WHERE id = $1 AND status = 'in_progress' AND attempts = $2`

	// pair is copied from the claim rather than joined: the row it came from is
	// the one being closed in this same transaction.
	const insertQuote = `
		INSERT INTO quotes (update_id, pair, rate, rate_date, fetched_at)
		VALUES ($1, $2, $3::numeric, $4, $5)`

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("complete task %s: begin: %w", claim.ID, err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	tag, err := tx.Exec(ctx, closeTask, claim.ID, claim.Attempts)
	if err != nil {
		return fmt.Errorf("complete task %s: close task: %w", claim.ID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("complete task %s: %w", claim.ID, domain.ErrStaleClaim)
	}

	if _, err := tx.Exec(ctx, insertQuote, claim.ID, claim.Pair, rate.String(), rateDate, fetchedAt); err != nil {
		return fmt.Errorf("complete task %s: insert quote: %w", claim.ID, err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("complete task %s: commit: %w", claim.ID, err)
	}

	return nil
}

// reason is served to clients as is, so it has to be a normalised message,
// never a raw provider error or an upstream URL. The caller owns that wording.
//
// claim carries the same proof of ownership as CompleteTask: failing a task
// that is no longer ours would overwrite the state of whoever holds it now.
func (r *Repository) FailTask(ctx context.Context, claim domain.UpdateTask, reason string) error {
	const query = `
		UPDATE quote_updates
		   SET status     = 'failed',
		       error      = $3,
		       updated_at = now()
		 WHERE id = $1 AND status = 'in_progress' AND attempts = $2`

	// The schema requires a failed task to carry a reason; an empty string
	// would pass that and tell a client nothing.
	if reason == "" {
		return fmt.Errorf("fail task %s: reason is empty", claim.ID)
	}

	tag, err := r.pool.Exec(ctx, query, claim.ID, claim.Attempts, reason)
	if err != nil {
		return fmt.Errorf("fail task %s: %w", claim.ID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("fail task %s: %w", claim.ID, domain.ErrStaleClaim)
	}

	return nil
}

// For a worker giving a task up rather than finishing it: on shutdown the task
// did not fail, so failing it would tell a client the provider was at fault.
//
// attempts is not decremented. It counts how many times processing was started,
// and one start did happen.
func (r *Repository) ReleaseTask(ctx context.Context, claim domain.UpdateTask) error {
	const query = `
		UPDATE quote_updates
		   SET status     = 'pending',
		       updated_at = now()
		 WHERE id = $1 AND status = 'in_progress' AND attempts = $2`

	tag, err := r.pool.Exec(ctx, query, claim.ID, claim.Attempts)
	if err != nil {
		return fmt.Errorf("release task %s: %w", claim.ID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("release task %s: %w", claim.ID, domain.ErrStaleClaim)
	}

	return nil
}

// Nothing releases a stuck task on its own: the row lock disappeared with the
// process that held it. Those under maxAttempts go back to the queue, the rest
// are closed as failed, which stops a task that reliably kills its worker from
// cycling forever.
//
// The counts are returned apart because they mean different things: releases
// say workers are dying, a failure says one task keeps killing whoever picks it
// up.
//
// One transaction for both statements, so they partition the table at the same
// instant -- now() is the transaction's start time, not the statement's.
func (r *Repository) ReleaseStuckTasks(
	ctx context.Context,
	olderThan time.Duration,
	maxAttempts int,
	reason string,
) (released, failed int, err error) {
	// The cutoff is now() minus an interval built from $1 seconds, so the age
	// is measured by the database clock rather than this container's.
	const releaseQuery = `
		UPDATE quote_updates
		   SET status     = 'pending',
		       updated_at = now()
		 WHERE status = 'in_progress'
		   AND attempts < $2
		   AND updated_at < now() - make_interval(secs => $1)`

	// attempts is left alone: it counts claims, and the next claim increments
	// it.
	const abandonQuery = `
		UPDATE quote_updates
		   SET status     = 'failed',
		       error      = $3,
		       updated_at = now()
		 WHERE status = 'in_progress'
		   AND attempts >= $2
		   AND updated_at < now() - make_interval(secs => $1)`

	if reason == "" {
		return 0, 0, errors.New("release stuck tasks: reason is empty")
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	seconds := olderThan.Seconds()

	releaseTag, err := tx.Exec(ctx, releaseQuery, seconds, maxAttempts)
	if err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: release: %w", err)
	}

	abandonTag, err := tx.Exec(ctx, abandonQuery, seconds, maxAttempts, reason)
	if err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: abandon: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: commit: %w", err)
	}

	return int(releaseTag.RowsAffected()), int(abandonTag.RowsAffected()), nil
}

// The column order below is the order every query above selects in.
func scanTask(row pgx.Row) (domain.UpdateTask, error) {
	var t domain.UpdateTask

	if err := row.Scan(&t.ID, &t.Pair, &t.Status, &t.Attempts, &t.Error, &t.CreatedAt, &t.UpdatedAt); err != nil {
		return domain.UpdateTask{}, err
	}

	return t, nil
}
