package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	"github.com/llukmann/currency-quotes-service/internal/domain"
)

// Repository is the whole of the service's persistence: the queue of update
// tasks and the quotes they produce. The two tables sit behind one type
// because the quotes table is written only by the finalisation of a task, and
// because every statement that moves a task between statuses then lives in one
// file and can be read as a set -- each of them has to carry
// updated_at = now(), and nothing in the schema enforces that.
type Repository struct {
	pool *pgxpool.Pool
}

// NewRepository returns a repository backed by pool. The pool is owned by the
// caller, which also closes it.
func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{pool: pool}
}

// uniqueViolation is the SQLSTATE Postgres reports for a duplicate key.
//
// Spelled out rather than taken from jackc/pgerrcode, which does sit in the
// module graph already -- but only because the migration driver happens to use
// it. Importing it here would turn a by-product of somebody else's choice into
// a requirement of ours, and the code it names has been fixed by the standard
// for longer than either library has existed.
const uniqueViolation = "23505"

// querier is the part of pgx that does not care whether it is addressing the
// pool or a transaction, so that one statement can be issued from either.
type querier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// isUniqueViolation reports a duplicate key raised by Postgres, however the
// driver wrapped it on the way up.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError

	return errors.As(err, &pgErr) && pgErr.Code == uniqueViolation
}

// CreateTask queues a refresh of pair and returns the task that answers the
// request, which is not always a new one. The identifier and the timestamps
// come from the database, so what comes back is the row a client will later be
// shown.
//
// Two things deduplicate here and they cover different windows. The partial
// unique index on pair catches posts colliding while a task is unfinished,
// whoever sent them; the key catches one client sending the same request twice,
// which is the commoner case -- a task is usually finished long before a client
// gets round to retrying.
//
// key is nil when no Idempotency-Key was sent, and then one statement does the
// whole job. With a key the task and the binding are written in a single
// transaction, so that rolling back takes the task with it: were the binding
// written afterwards, a lost race would leave a task behind whose identifier
// reached nobody and which nobody will ever ask about.
//
// Returns domain.ErrKeyConflict if the key is already bound to a task for a
// different pair.
func (r *Repository) CreateTask(ctx context.Context, pair domain.Pair, key *uuid.UUID) (domain.UpdateTask, error) {
	if key == nil {
		return insertTask(ctx, r.pool, pair)
	}

	// A fast path and nothing more: it answers the repeat arriving seconds
	// later, which is the case the whole mechanism exists for, without opening
	// a transaction to find out. What makes the answer right when two requests
	// race is the unique constraint below, never this read.
	task, found, err := r.taskByKey(ctx, *key)
	if err != nil {
		return domain.UpdateTask{}, err
	}
	if found {
		return replayTask(task, pair)
	}

	return r.createTaskWithKey(ctx, pair, *key)
}

// createTaskWithKey writes the task and the binding to it as one unit.
func (r *Repository) createTaskWithKey(ctx context.Context, pair domain.Pair, key uuid.UUID) (domain.UpdateTask, error) {
	const bindQuery = `INSERT INTO idempotency_keys (key, update_id) VALUES ($1, $2)`

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return domain.UpdateTask{}, fmt.Errorf("create task: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// The order is forced rather than chosen: the identifier is generated by
	// the database, so there is nothing to bind a key to until the task exists.
	task, err := insertTask(ctx, tx, pair)
	if err != nil {
		return domain.UpdateTask{}, err
	}

	if _, err := tx.Exec(ctx, bindQuery, key, task.ID); err != nil {
		if !isUniqueViolation(err) {
			return domain.UpdateTask{}, fmt.Errorf("create task: bind key: %w", err)
		}

		// Somebody bound this key first. Rolling back drops the task written a
		// moment ago along with it, which is the whole reason both are here.
		//
		// The winner has committed by now, and that is not an assumption: an
		// insert conflicting with an uncommitted duplicate waits for the other
		// transaction to end, so arriving at this line means it ended by
		// committing rather than by rolling back.
		if err := tx.Rollback(ctx); err != nil {
			return domain.UpdateTask{}, fmt.Errorf("create task: rollback: %w", err)
		}

		return r.replayByKey(ctx, key, pair)
	}

	if err := tx.Commit(ctx); err != nil {
		return domain.UpdateTask{}, fmt.Errorf("create task: commit: %w", err)
	}

	return task, nil
}

// replayByKey answers a post whose key turned out to be bound already.
func (r *Repository) replayByKey(ctx context.Context, key uuid.UUID, pair domain.Pair) (domain.UpdateTask, error) {
	task, found, err := r.taskByKey(ctx, key)
	if err != nil {
		return domain.UpdateTask{}, err
	}
	if !found {
		// Only reachable if the sweep removed the binding between the conflict
		// and this read, which needs it to have been past its lifetime already
		// when it was written. Reported rather than retried around: it would
		// mean the sweep and the insert disagree about what exists.
		return domain.UpdateTask{}, fmt.Errorf("create task: key %s conflicted but holds no binding", key)
	}

	return replayTask(task, pair)
}

// replayTask answers with the task a key is bound to, provided it was the same
// request. The pair of the bound task is enough to tell, since a key is only
// ever bound to a task queued for the pair it arrived with.
func replayTask(task domain.UpdateTask, pair domain.Pair) (domain.UpdateTask, error) {
	if task.Pair != pair {
		return domain.UpdateTask{}, domain.ErrKeyConflict
	}

	return task, nil
}

// taskByKey returns the task an idempotency key is bound to. The join is what
// keeps the answer to one round trip, and it is also what keeps it current: the
// status served beside the identifier has to be the one the task carries now,
// not the one it was created in.
//
// Age is deliberately not part of the condition. The sweep is the only thing
// that ends a binding, so a row that is here is a binding that holds -- and a
// predicate here would disagree with the insert, which collides with rows the
// sweep has not reached yet.
func (r *Repository) taskByKey(ctx context.Context, key uuid.UUID) (domain.UpdateTask, bool, error) {
	const query = `
		SELECT u.id, u.pair, u.status, u.attempts, COALESCE(u.error, ''), u.created_at, u.updated_at
		  FROM idempotency_keys k
		  JOIN quote_updates u ON u.id = k.update_id
		 WHERE k.key = $1`

	task, err := scanTask(r.pool.QueryRow(ctx, query, key))
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.UpdateTask{}, false, nil
	}
	if err != nil {
		return domain.UpdateTask{}, false, fmt.Errorf("task by key %s: %w", key, err)
	}

	return task, true, nil
}

// insertTask queues a refresh of pair, or answers with the unfinished task that
// already covers it.
//
// The conflict is resolved by an update that changes nothing, purely so that
// the statement has a row to return. DO NOTHING returns none, and fetching the
// other task with a second query opens a window in which that task finishes --
// whereupon the query finds nothing and the whole thing starts over.
//
// What the assignment must never touch is updated_at. For a task in progress
// that column is the recovery pass's clock, and posts on a busy pair would push
// the threshold ahead of itself for as long as they kept arriving, leaving a
// task abandoned by a dead worker to sit in progress forever.
func insertTask(ctx context.Context, q querier, pair domain.Pair) (domain.UpdateTask, error) {
	const query = `
		INSERT INTO quote_updates (pair)
		VALUES ($1)
		ON CONFLICT (pair) WHERE status IN ('pending', 'in_progress')
		DO UPDATE SET pair = quote_updates.pair
		RETURNING id, pair, status, attempts, COALESCE(error, ''), created_at, updated_at`

	t, err := scanTask(q.QueryRow(ctx, query, pair))
	if err != nil {
		return domain.UpdateTask{}, fmt.Errorf("create task: %w", err)
	}

	return t, nil
}

// GetTask returns the task and, once it has completed successfully, the rate it
// produced. It backs GET /quotes/updates/{id}, the endpoint a client polls, and
// that is its only caller: a worker carries its task in hand and never reads it
// back. The join keeps the answer to a single round trip, and a quote row
// exists for precisely the tasks in StatusDone, since the finalisation writes
// both in one transaction.
//
// Returns domain.ErrNotFound if no such task exists.
func (r *Repository) GetTask(ctx context.Context, id uuid.UUID) (domain.TaskDetails, error) {
	const query = `
		SELECT u.id, u.pair, u.status, u.attempts, COALESCE(u.error, ''), u.created_at, u.updated_at,
		       q.update_id, q.pair, q.rate::text, q.rate_date, q.fetched_at
		  FROM quote_updates u
		  LEFT JOIN quotes q ON q.update_id = u.id
		 WHERE u.id = $1`

	var (
		d domain.TaskDetails
		// Null for every task that has not completed, hence the pointers.
		quoteID   *uuid.UUID
		quotePair *domain.Pair
		rawRate   *string
		rateDate  *time.Time
		fetchedAt *time.Time
	)

	err := r.pool.QueryRow(ctx, query, id).Scan(
		&d.Task.ID, &d.Task.Pair, &d.Task.Status, &d.Task.Attempts,
		&d.Task.Error, &d.Task.CreatedAt, &d.Task.UpdatedAt,
		&quoteID, &quotePair, &rawRate, &rateDate, &fetchedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.TaskDetails{}, fmt.Errorf("get task %s: %w", id, domain.ErrNotFound)
	}
	if err != nil {
		return domain.TaskDetails{}, fmt.Errorf("get task %s: %w", id, err)
	}

	if quoteID == nil {
		return d, nil
	}

	rate, err := decimal.NewFromString(*rawRate)
	if err != nil {
		return domain.TaskDetails{}, fmt.Errorf("get task %s: parse rate %q: %w", id, *rawRate, err)
	}

	d.Quote = &domain.Quote{
		UpdateID:  *quoteID,
		Pair:      *quotePair,
		Rate:      rate,
		RateDate:  *rateDate,
		FetchedAt: *fetchedAt,
	}

	return d, nil
}

// GetLatestQuote returns the most recently fetched rate for pair, whichever
// task produced it.
//
// Returns domain.ErrNotFound if the pair has never been quoted.
func (r *Repository) GetLatestQuote(ctx context.Context, pair domain.Pair) (domain.Quote, error) {
	// Ordered by fetched_at rather than rate_date: a weekend leaves several
	// rows sharing one rate_date, and their order would be undefined. Both the
	// filter and the ordering are served by quotes_pair_fetched_at_idx.
	const query = `
		SELECT update_id, pair, rate::text, rate_date, fetched_at
		  FROM quotes
		 WHERE pair = $1
		 ORDER BY fetched_at DESC
		 LIMIT 1`

	var (
		q       domain.Quote
		rawRate string
	)

	err := r.pool.QueryRow(ctx, query, pair).Scan(&q.UpdateID, &q.Pair, &rawRate, &q.RateDate, &q.FetchedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Quote{}, fmt.Errorf("get latest quote for %s: %w", pair, domain.ErrNotFound)
	}
	if err != nil {
		return domain.Quote{}, fmt.Errorf("get latest quote for %s: %w", pair, err)
	}

	if q.Rate, err = decimal.NewFromString(rawRate); err != nil {
		return domain.Quote{}, fmt.Errorf("get latest quote for %s: parse rate %q: %w", pair, rawRate, err)
	}

	return q, nil
}

// ClaimTask takes the oldest waiting task, marks it in progress and returns it.
// The second result is false when there is nothing to do, which is the normal
// state of an idle worker rather than an error.
//
// Selecting and marking are one statement on purpose: read the row first and
// mark it second, and another worker reads it in between, so the provider is
// called twice for one task. SKIP LOCKED is what makes a pool of workers worth
// having -- without it they would queue up behind the same oldest row and run
// as one.
//
// The row lock lasts only until this statement's transaction commits, so from
// then on the only thing saying the task is taken is its status. That is why
// the recovery pass has to exist, and why CompleteTask and FailTask have to
// prove the claim they hold is still current.
func (r *Repository) ClaimTask(ctx context.Context) (domain.UpdateTask, bool, error) {
	// attempts is incremented here rather than on failure: it counts how many
	// times processing was started, which is what bounds the recovery loop, and
	// it identifies this particular claim to the finalisation below.
	const query = `
		UPDATE quote_updates
		   SET status     = 'in_progress',
		       attempts   = attempts + 1,
		       updated_at = now()
		 WHERE id = (
		       SELECT id
		         FROM quote_updates
		        WHERE status = 'pending'
		        ORDER BY created_at
		        LIMIT 1
		          FOR UPDATE SKIP LOCKED
		 )
		RETURNING id, pair, status, attempts, COALESCE(error, ''), created_at, updated_at`

	t, err := scanTask(r.pool.QueryRow(ctx, query))
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.UpdateTask{}, false, nil
	}
	if err != nil {
		return domain.UpdateTask{}, false, fmt.Errorf("claim task: %w", err)
	}

	return t, true, nil
}

// CompleteTask stores the fetched rate and closes the task in one transaction:
// a quote whose task is not finished would be served by GET /quotes/latest
// under a task that still claims to be running.
//
// claim must be the task as ClaimTask returned it. Its attempts value
// identifies that claim, and the statement matches on it, so a worker whose
// task was taken away by the recovery pass -- and possibly claimed by someone
// else since, which restores the status and leaves a status check alone
// useless -- changes nothing and gets domain.ErrStaleClaim. This match is what
// carries the guarantee; the staleness threshold only decides how often the
// case arises, since it weighs a budget measured by this process against wall
// time measured by the database.
//
// The task is closed before the quote is inserted, so that a lost claim leaves
// no row behind in quotes.
func (r *Repository) CompleteTask(
	ctx context.Context,
	claim domain.UpdateTask,
	rate decimal.Decimal,
	rateDate time.Time,
	fetchedAt time.Time,
) error {
	const closeTask = `
		UPDATE quote_updates
		   SET status     = 'done',
		       error      = NULL,
		       updated_at = now()
		 WHERE id = $1 AND status = 'in_progress' AND attempts = $2`

	// pair is copied from the claim, which is the only source of it here: the
	// denormalised column cannot drift from the task it belongs to. The rate
	// crosses as text, so no binary float is involved on the way into numeric.
	const insertQuote = `
		INSERT INTO quotes (update_id, pair, rate, rate_date, fetched_at)
		VALUES ($1, $2, $3::numeric, $4, $5)`

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("complete task %s: begin: %w", claim.ID, err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	tag, err := tx.Exec(ctx, closeTask, claim.ID, claim.Attempts)
	if err != nil {
		return fmt.Errorf("complete task %s: close task: %w", claim.ID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("complete task %s: %w", claim.ID, domain.ErrStaleClaim)
	}

	if _, err := tx.Exec(ctx, insertQuote, claim.ID, claim.Pair, rate.String(), rateDate, fetchedAt); err != nil {
		return fmt.Errorf("complete task %s: insert quote: %w", claim.ID, err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("complete task %s: commit: %w", claim.ID, err)
	}

	return nil
}

// FailTask closes the task as failed with reason, which is served to clients as
// is: it has to be a normalised message, never a raw provider error or an
// upstream URL. The caller owns that wording, since what a client reads is a
// decision of the layer above this one.
//
// claim carries the same proof of ownership as in CompleteTask, and a lost
// claim is reported the same way. Failing a task that is no longer ours would
// overwrite the state of whoever holds it now.
func (r *Repository) FailTask(ctx context.Context, claim domain.UpdateTask, reason string) error {
	const query = `
		UPDATE quote_updates
		   SET status     = 'failed',
		       error      = $3,
		       updated_at = now()
		 WHERE id = $1 AND status = 'in_progress' AND attempts = $2`

	// The schema requires a failed task to carry a reason; an empty string
	// satisfies that constraint while telling a client nothing.
	if reason == "" {
		return fmt.Errorf("fail task %s: reason is empty", claim.ID)
	}

	tag, err := r.pool.Exec(ctx, query, claim.ID, claim.Attempts, reason)
	if err != nil {
		return fmt.Errorf("fail task %s: %w", claim.ID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("fail task %s: %w", claim.ID, domain.ErrStaleClaim)
	}

	return nil
}

// ReleaseTask puts a claimed task back in the queue, for a worker that is
// giving it up rather than finishing it: on shutdown the task did not fail and
// nobody is at fault, so failing it would tell a client the provider was.
//
// claim carries the same proof of ownership as the two above, and for the same
// reason: without it a worker leaving late would take the task away from
// whoever claimed it after the recovery pass released it.
//
// attempts is not decremented. It counts how many times processing was
// started, and one start did happen; the recovery pass leaves it alone for the
// same reason, and the next claim is what moves it on.
func (r *Repository) ReleaseTask(ctx context.Context, claim domain.UpdateTask) error {
	const query = `
		UPDATE quote_updates
		   SET status     = 'pending',
		       updated_at = now()
		 WHERE id = $1 AND status = 'in_progress' AND attempts = $2`

	tag, err := r.pool.Exec(ctx, query, claim.ID, claim.Attempts)
	if err != nil {
		return fmt.Errorf("release task %s: %w", claim.ID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("release task %s: %w", claim.ID, domain.ErrStaleClaim)
	}

	return nil
}

// ReleaseStuckTasks deals with tasks left in progress by a worker that died
// before finalising them: nothing releases those on their own, since the row
// lock disappeared along with the process. A task counts as stuck once it has
// been in progress for longer than olderThan.
//
// Tasks below maxAttempts go back to the queue; those that have reached it are
// closed as failed with reason, which is what stops a task that reliably kills
// its worker from cycling between claim and release forever. All three are
// settings rather than constants, and they arrive as arguments because the
// caller is the one holding the configuration: how long to wait, how many
// claims to allow and what to tell a client are not decisions for storage.
//
// The two counts are returned apart because they mean different things to
// whoever logs them. A steady trickle of releases says workers are dying or
// that the threshold is too tight; a failure says one task keeps killing
// whoever picks it up. A single total would hide both.
//
// The two statements share one transaction so that both partition the table at
// the same instant: now() is the transaction's start time, not the statement's.
// Age is measured by the database clock throughout -- a cutoff computed here
// would weigh the database's timestamps against this container's clock.
func (r *Repository) ReleaseStuckTasks(
	ctx context.Context,
	olderThan time.Duration,
	maxAttempts int,
	reason string,
) (released, failed int, err error) {
	// The cutoff is now() minus an interval built from $1 seconds. Written this
	// way the column stays bare on the left and the right side is one value for
	// the whole transaction, so the partial index on updated_at serves the
	// condition as a range. Turned around -- extracting each row's age and
	// comparing that to $1 -- it would be an expression over the column, and
	// every row would have to be computed.
	const releaseQuery = `
		UPDATE quote_updates
		   SET status     = 'pending',
		       updated_at = now()
		 WHERE status = 'in_progress'
		   AND attempts < $2
		   AND updated_at < now() - make_interval(secs => $1)`

	// attempts is left alone: it counts claims, and the next claim increments
	// it.
	const abandonQuery = `
		UPDATE quote_updates
		   SET status     = 'failed',
		       error      = $3,
		       updated_at = now()
		 WHERE status = 'in_progress'
		   AND attempts >= $2
		   AND updated_at < now() - make_interval(secs => $1)`

	if reason == "" {
		return 0, 0, errors.New("release stuck tasks: reason is empty")
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	seconds := olderThan.Seconds()

	releaseTag, err := tx.Exec(ctx, releaseQuery, seconds, maxAttempts)
	if err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: release: %w", err)
	}

	abandonTag, err := tx.Exec(ctx, abandonQuery, seconds, maxAttempts, reason)
	if err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: abandon: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return 0, 0, fmt.Errorf("release stuck tasks: commit: %w", err)
	}

	return int(releaseTag.RowsAffected()), int(abandonTag.RowsAffected()), nil
}

// DeleteExpiredKeys removes idempotency bindings older than olderThan and
// reports how many went.
//
// This is the only thing that ends a binding, which is what makes the presence
// of a row the whole of the question a lookup asks. It follows that the sweep
// running late stretches a lifetime rather than breaking one, and that it can
// fail or be cut short without the contract moving.
func (r *Repository) DeleteExpiredKeys(ctx context.Context, olderThan time.Duration) (int, error) {
	// A sequential scan by design: created_at carries no index, which would
	// cost on every insert -- the hot path of a post -- to hurry a sweep nobody
	// is waiting on. Age is measured by the database clock as everywhere else,
	// since a cutoff computed here would weigh the database's timestamps
	// against this container's.
	const query = `DELETE FROM idempotency_keys WHERE created_at < now() - make_interval(secs => $1)`

	tag, err := r.pool.Exec(ctx, query, olderThan.Seconds())
	if err != nil {
		return 0, fmt.Errorf("delete expired keys: %w", err)
	}

	return int(tag.RowsAffected()), nil
}

// scanTask reads the columns of quote_updates in the order the queries above
// list them.
func scanTask(row pgx.Row) (domain.UpdateTask, error) {
	var t domain.UpdateTask

	if err := row.Scan(&t.ID, &t.Pair, &t.Status, &t.Attempts, &t.Error, &t.CreatedAt, &t.UpdatedAt); err != nil {
		return domain.UpdateTask{}, err
	}

	return t, nil
}
