// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternalError  ErrorCode = "internal_error"
	ErrorCodeInvalidPair    ErrorCode = "invalid_pair"
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeKeyConflict    ErrorCode = "key_conflict"
	ErrorCodeNotFound       ErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidPair:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeKeyConflict:
		return true
	case ErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	Done       Status = "done"
	Failed     Status = "failed"
	InProgress Status = "in_progress"
	Pending    Status = "pending"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// AcceptedResponse Two fields and no more. A rate here would invite reading this endpoint
// as a synchronous quote, which is the one thing the asynchronous
// contract exists to prevent, and the reason a task failed belongs to
// `GET /quotes/updates/{id}`, which is the only place that keeps it.
type AcceptedResponse struct {
	// Status The state of an update. `pending` and `in_progress` both mean the
	// refresh has not finished and are equivalent to a client waiting for it;
	// `done` and `failed` are terminal.
	//
	//
	// Example: pending
	Status Status `json:"status"`

	// UpdateId Identifier of an update, assigned when it is queued.
	//
	// Example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
	UpdateId UpdateId `json:"update_id"`
}

// CreateUpdateRequest defines model for CreateUpdateRequest.
type CreateUpdateRequest struct {
	// Pair A currency pair written BASE/QUOTE. Both currencies have to be USD, EUR
	// or MXN, and they have to differ.
	//
	// In a request the case does not matter, so `eur/mxn` names the same pair
	// as `EUR/MXN`. In an answer the pair is always upper case.
	//
	//
	// Example: EUR/MXN
	Pair Pair `json:"pair"`
}

// Error The single error envelope of this API: every failure of every endpoint
// is shaped like this, so a client parses one thing.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code A stable, machine-readable identifier of what went wrong. A client
	// branches on this; the set is closed.
	Code ErrorCode `json:"code"`

	// Message The same failure written for a person. Not part of the contract:
	// the wording may change where the code does not.
	//
	//
	// Example: invalid currency pair: unsupported currency "RUB"
	Message string `json:"message"`
}

// ErrorCode A stable, machine-readable identifier of what went wrong. A client
// branches on this; the set is closed.
type ErrorCode string

// FetchedAt When this service received the rate, in UTC and to the second. Together
// with `rate_date` it separates a stale rate from a stale service: over a
// weekend two updates return the same rate and the same `rate_date`, and
// only this field says both of them ran.
//
// Example: 2026-09-05T14:32:07Z
type FetchedAt = time.Time

// Pair A currency pair written BASE/QUOTE. Both currencies have to be USD, EUR
// or MXN, and they have to differ.
//
// In a request the case does not matter, so `eur/mxn` names the same pair
// as `EUR/MXN`. In an answer the pair is always upper case.
//
// Example: EUR/MXN
type Pair = string

// QuoteResponse The last rate stored for a pair, with the update it came from.
type QuoteResponse struct {
	// FetchedAt When this service received the rate, in UTC and to the second. Together
	// with `rate_date` it separates a stale rate from a stale service: over a
	// weekend two updates return the same rate and the same `rate_date`, and
	// only this field says both of them ran.
	//
	//
	// Example: 2026-09-05T14:32:07Z
	FetchedAt FetchedAt `json:"fetched_at"`

	// Pair A currency pair written BASE/QUOTE. Both currencies have to be USD, EUR
	// or MXN, and they have to differ.
	//
	// In a request the case does not matter, so `eur/mxn` names the same pair
	// as `EUR/MXN`. In an answer the pair is always upper case.
	//
	//
	// Example: EUR/MXN
	Pair Pair `json:"pair"`

	// Rate How many units of the quote currency one unit of the base currency
	// buys, with the ten decimal places it is stored with.
	//
	// Served as a string rather than a JSON number on purpose: most clients
	// parse a JSON number into a float64, and a rate that survives that round
	// trip intact is a coincidence.
	//
	//
	// Example: 20.1394500000
	Rate Rate `json:"rate"`

	// RateDate The day the rate is valid for, as the provider states it. Reference
	// rates are daily and published on working days only, so this can lag
	// behind `fetched_at` by several days over a weekend.
	//
	//
	// Example: 2026-09-04
	RateDate RateDate `json:"rate_date"`

	// UpdateId Identifier of an update, assigned when it is queued.
	//
	// Example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
	UpdateId UpdateId `json:"update_id"`
}

// Rate How many units of the quote currency one unit of the base currency
// buys, with the ten decimal places it is stored with.
//
// Served as a string rather than a JSON number on purpose: most clients
// parse a JSON number into a float64, and a rate that survives that round
// trip intact is a coincidence.
//
// Example: 20.1394500000
type Rate = string

// RateDate The day the rate is valid for, as the provider states it. Reference
// rates are daily and published on working days only, so this can lag
// behind `fetched_at` by several days over a weekend.
//
// Example: 2026-09-04
type RateDate = openapi_types.Date

// Status The state of an update. `pending` and `in_progress` both mean the
// refresh has not finished and are equivalent to a client waiting for it;
// `done` and `failed` are terminal.
//
// Example: pending
type Status string

// TaskResponse An update and whatever it has produced so far.
//
// The last four fields depend on the status: a task still queued carries
// none of them, a completed one carries the rate and its two dates, and a
// failed one carries the reason it failed.
type TaskResponse struct {
	// Error Why the refresh failed, present on a failed task alone. Written for
	// a person; a client branching on the outcome reads the status.
	//
	//
	// Example: provider unavailable after 3 attempts
	Error *string `json:"error,omitempty"`

	// FetchedAt When this service received the rate, in UTC and to the second. Together
	// with `rate_date` it separates a stale rate from a stale service: over a
	// weekend two updates return the same rate and the same `rate_date`, and
	// only this field says both of them ran.
	//
	//
	// Example: 2026-09-05T14:32:07Z
	FetchedAt *FetchedAt `json:"fetched_at,omitempty"`

	// Pair A currency pair written BASE/QUOTE. Both currencies have to be USD, EUR
	// or MXN, and they have to differ.
	//
	// In a request the case does not matter, so `eur/mxn` names the same pair
	// as `EUR/MXN`. In an answer the pair is always upper case.
	//
	//
	// Example: EUR/MXN
	Pair Pair `json:"pair"`

	// Rate How many units of the quote currency one unit of the base currency
	// buys, with the ten decimal places it is stored with.
	//
	// Served as a string rather than a JSON number on purpose: most clients
	// parse a JSON number into a float64, and a rate that survives that round
	// trip intact is a coincidence.
	//
	//
	// Example: 20.1394500000
	Rate *Rate `json:"rate,omitempty"`

	// RateDate The day the rate is valid for, as the provider states it. Reference
	// rates are daily and published on working days only, so this can lag
	// behind `fetched_at` by several days over a weekend.
	//
	//
	// Example: 2026-09-04
	RateDate *RateDate `json:"rate_date,omitempty"`

	// Status The state of an update. `pending` and `in_progress` both mean the
	// refresh has not finished and are equivalent to a client waiting for it;
	// `done` and `failed` are terminal.
	//
	//
	// Example: pending
	Status Status `json:"status"`

	// UpdateId Identifier of an update, assigned when it is queued.
	//
	// Example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
	UpdateId UpdateId `json:"update_id"`
}

// UpdateId Identifier of an update, assigned when it is queued.
//
// Example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
type UpdateId = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// PairQuery A currency pair written BASE/QUOTE. Both currencies have to be USD, EUR
// or MXN, and they have to differ.
//
// In a request the case does not matter, so `eur/mxn` names the same pair
// as `EUR/MXN`. In an answer the pair is always upper case.
//
// Example: EUR/MXN
type PairQuery = Pair

// UpdateIdPath Identifier of an update, assigned when it is queued.
//
// Example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
type UpdateIdPath = UpdateId

// InternalError The single error envelope of this API: every failure of every endpoint
// is shaped like this, so a client parses one thing.
type InternalError = Error

// GetLatestQuoteParams defines parameters for GetLatestQuote.
type GetLatestQuoteParams struct {
	// Pair The pair to read. The slash may be sent literally (`?pair=EUR/MXN`) or
	// percent-encoded (`?pair=EUR%2FMXN`).
	Pair PairQuery `form:"pair" json:"pair"`
}

// CreateQuoteUpdateParams defines parameters for CreateQuoteUpdate.
type CreateQuoteUpdateParams struct {
	// IdempotencyKey A UUID naming one intent of one client. Optional: without it a post is
	// still deduplicated against unfinished work on the same pair, but only a
	// key tells a retry of one request apart from a fresh request for the
	// same thing.
	//
	// A repeat carrying the same key is answered with the original task and
	// the same 202, whatever became of that task since. A new attempt at a
	// refresh is a new intent and needs a new key.
	//
	// The binding between a key and its task lives for a configurable time,
	// an hour by default. Past that the key is a stranger again and queues a
	// new task.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateQuoteUpdateJSONRequestBody defines body for CreateQuoteUpdate for application/json ContentType.
type CreateQuoteUpdateJSONRequestBody = CreateUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetLatestQuote Read the last known rate of a pair
	// (GET /quotes/latest)
	GetLatestQuote(w http.ResponseWriter, r *http.Request, params GetLatestQuoteParams)
	// CreateQuoteUpdate Queue a quote update
	// (POST /quotes/updates)
	CreateQuoteUpdate(w http.ResponseWriter, r *http.Request, params CreateQuoteUpdateParams)
	// GetQuoteUpdate Read the state of an update
	// (GET /quotes/updates/{id})
	GetQuoteUpdate(w http.ResponseWriter, r *http.Request, id UpdateIdPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetLatestQuote Read the last known rate of a pair
// (GET /quotes/latest)
func (_ Unimplemented) GetLatestQuote(w http.ResponseWriter, r *http.Request, params GetLatestQuoteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateQuoteUpdate Queue a quote update
// (POST /quotes/updates)
func (_ Unimplemented) CreateQuoteUpdate(w http.ResponseWriter, r *http.Request, params CreateQuoteUpdateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetQuoteUpdate Read the state of an update
// (GET /quotes/updates/{id})
func (_ Unimplemented) GetQuoteUpdate(w http.ResponseWriter, r *http.Request, id UpdateIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLatestQuote operation middleware
func (siw *ServerInterfaceWrapper) GetLatestQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestQuoteParams

	// ------------- Required query parameter "pair" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pair", r.URL.Query(), &params.Pair, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pair"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pair", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuoteUpdate operation middleware
func (siw *ServerInterfaceWrapper) CreateQuoteUpdate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateQuoteUpdateParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuoteUpdate(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuoteUpdate operation middleware
func (siw *ServerInterfaceWrapper) GetQuoteUpdate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UpdateIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuoteUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/quotes/updates", wrapper.CreateQuoteUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/quotes/updates/{id}", wrapper.GetQuoteUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/quotes/latest", wrapper.GetLatestQuote)
	})

	return r
}
